steps:
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-latest || true
        docker pull gcr.io/$PROJECT_ID/rshell:master-builder-latest || true

        docker build -t gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-latest \
          --cache-from gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-latest \
          --cache-from gcr.io/$PROJECT_ID/rshell:master-builder-latest \
          --target builder .
  - name: "gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-$SHORT_SHA"
    entrypoint: "sh"
    args:
      - "-c"
      - |
        go test ./...
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker pull gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-latest || true
        docker pull gcr.io/$PROJECT_ID/rshell:master-builder-latest || true

        docker build -t gcr.io/$PROJECT_ID/rshell:$SHORT_SHA \
          --cache-from gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-$SHORT_SHA \
          --cache-from gcr.io/$PROJECT_ID/rshell:master-builder-latest .

        if [[ "$BRANCH_NAME" == "master" ]]; then
          docker tag gcr.io/$PROJECT_ID/rshell:$SHORT_SHA gcr.io/$PROJECT_ID/rshell:latest
          docker push gcr.io/$PROJECT_ID/rshell:latest
        else
          exit 0
        fi
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        if [[ "$BRANCH_NAME" == "master" ]]; then
          gcloud components install beta
          gcloud beta run deploy rshell \
            --image gcr.io/$PROJECT_ID/rshell:latest \
            --allow-unauthenticated \
            --region=us-central1 \
            --platform=managed \
            --project=$PROJECT_ID
        else
          exit 0
        fi
images:
  - "gcr.io/$PROJECT_ID/rshell:$SHORT_SHA"
  - "gcr.io/$PROJECT_ID/rshell:$BRANCH_NAME-builder-latest"
